const DESKTOP_MOVIE_DISPLAY_LIMIT = 4;
const TABLET_MOVIE_DISPLAY_LIMIT = 2;
const MOBILE_MOVIE_DISPLAY_LIMIT = 2;
const MAX_SHORT_MOVIE_LENGTH = 40;
const EMAIL_PATTERN =
  "^[A-Za-z0-9\\._%\\+\\-]+@([A-Za-z0-9\\-]+\\.)+[A-Za-z]{2,}$";

export {
  DESKTOP_MOVIE_DISPLAY_LIMIT,
  TABLET_MOVIE_DISPLAY_LIMIT,
  MOBILE_MOVIE_DISPLAY_LIMIT,
  MAX_SHORT_MOVIE_LENGTH,
  EMAIL_PATTERN,
};
